[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sqlx]
version = "0.6.2"
default-features = false
features = [ "runtime-actix-rustls", "macros", "sqlite", "chrono", "decimal", "offline", "uuid", "json" ]


[dependencies]
actix-web = "4.1.0"
actix-rt = "2.7.0"
actix-service = "1.0.6"
actix-cors = "0.6.1"
log = "0.4.14"
env_logger = "0.9.0"
serde = "1.0.123"
serde_derive = "1.0.123"
serde_json = "1.0.62"
serde_qs = "0.8.2"
dotenv = "0.15.0"
futures = "0.3.12"
failure = "0.1.8"
derive_more = "0.99.11"
jsonwebtoken = "7.2.0"
bcrypt = "0.10.1"
censor = "0.3.0"
rand = "0.8.5"
bitflags = "1.3.2"
thiserror = "1.0.38"
ory-client = "1.1.33"
validator = { version = "0.15", features = ["derive"] }

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.uuid]
version = "0.8.2"
features = ["v4"]
