/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Audit
 */
export interface Audit {
    /**
     * 
     * @type {string}
     * @memberof Audit
     */
    auditor: string;
    /**
     * The body of the audit
     * @type {string}
     * @memberof Audit
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof Audit
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Audit
     */
    projectId: string;
    /**
     * The datetime the audit was created
     * @type {Date}
     * @memberof Audit
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the Audit interface.
 */
export function instanceOfAudit(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "auditor" in value;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function AuditFromJSON(json: any): Audit {
    return AuditFromJSONTyped(json, false);
}

export function AuditFromJSONTyped(json: any, ignoreDiscriminator: boolean): Audit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auditor': json['auditor'],
        'body': json['body'],
        'id': json['id'],
        'projectId': json['project_id'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AuditToJSON(value?: Audit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auditor': value.auditor,
        'body': value.body,
        'id': value.id,
        'project_id': value.projectId,
        'timestamp': (value.timestamp.toISOString()),
    };
}

