/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface AuthenticatedUser
 */
export interface AuthenticatedUser {
    /**
     * 
     * @type {string}
     * @memberof AuthenticatedUser
     */
    token: string;
    /**
     * 
     * @type {User}
     * @memberof AuthenticatedUser
     */
    user: User;
}

/**
 * Check if a given object implements the AuthenticatedUser interface.
 */
export function instanceOfAuthenticatedUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function AuthenticatedUserFromJSON(json: any): AuthenticatedUser {
    return AuthenticatedUserFromJSONTyped(json, false);
}

export function AuthenticatedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'user': UserFromJSON(json['user']),
    };
}

export function AuthenticatedUserToJSON(value?: AuthenticatedUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'user': UserToJSON(value.user),
    };
}

