/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditTaskGroup
 */
export interface EditTaskGroup {
    /**
     * The task group's new name (3 -> 30 characters)
     * @type {string}
     * @memberof EditTaskGroup
     */
    name?: string | null;
    /**
     * The position of the task group in the project
     * If this field is present all other task groups
     * in the project above will be moved forwards to
     * ensure the order is still valid
     * @type {number}
     * @memberof EditTaskGroup
     */
    position?: number | null;
}

/**
 * Check if a given object implements the EditTaskGroup interface.
 */
export function instanceOfEditTaskGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EditTaskGroupFromJSON(json: any): EditTaskGroup {
    return EditTaskGroupFromJSONTyped(json, false);
}

export function EditTaskGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditTaskGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'position': !exists(json, 'position') ? undefined : json['position'],
    };
}

export function EditTaskGroupToJSON(value?: EditTaskGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'position': value.position,
    };
}

