/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditProject
 */
export interface EditProject {
    /**
     * The project's new icon's url
     * @type {string}
     * @memberof EditProject
     */
    iconUrl?: string | null;
    /**
     * The project's new name (3 -> 30 charachters)
     * @type {string}
     * @memberof EditProject
     */
    name?: string | null;
    /**
     * The project's new visibility
     * @type {number}
     * @memberof EditProject
     */
    publicPermissions?: number | null;
}

/**
 * Check if a given object implements the EditProject interface.
 */
export function instanceOfEditProject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EditProjectFromJSON(json: any): EditProject {
    return EditProjectFromJSONTyped(json, false);
}

export function EditProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iconUrl': !exists(json, 'icon_url') ? undefined : json['icon_url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'publicPermissions': !exists(json, 'public_permissions') ? undefined : json['public_permissions'],
    };
}

export function EditProjectToJSON(value?: EditProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'icon_url': value.iconUrl,
        'name': value.name,
        'public_permissions': value.publicPermissions,
    };
}

