/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubTaskBuilder
 */
export interface SubTaskBuilder {
    /**
     * 
     * @type {string}
     * @memberof SubTaskBuilder
     */
    body: string;
}

/**
 * Check if a given object implements the SubTaskBuilder interface.
 */
export function instanceOfSubTaskBuilder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;

    return isInstance;
}

export function SubTaskBuilderFromJSON(json: any): SubTaskBuilder {
    return SubTaskBuilderFromJSONTyped(json, false);
}

export function SubTaskBuilderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubTaskBuilder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function SubTaskBuilderToJSON(value?: SubTaskBuilder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
    };
}

