/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskBuilder
 */
export interface TaskBuilder {
    /**
     * The task's accent colour (hex) - progress bar
     * @type {string}
     * @memberof TaskBuilder
     */
    accentColour: string;
    /**
     * The name of the task (3 -> 90 characters)
     * @type {string}
     * @memberof TaskBuilder
     */
    name: string;
    /**
     * The task's primary colour (hex) - background
     * @type {string}
     * @memberof TaskBuilder
     */
    primaryColour: string;
}

/**
 * Check if a given object implements the TaskBuilder interface.
 */
export function instanceOfTaskBuilder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accentColour" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "primaryColour" in value;

    return isInstance;
}

export function TaskBuilderFromJSON(json: any): TaskBuilder {
    return TaskBuilderFromJSONTyped(json, false);
}

export function TaskBuilderFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskBuilder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accentColour': json['accent_colour'],
        'name': json['name'],
        'primaryColour': json['primary_colour'],
    };
}

export function TaskBuilderToJSON(value?: TaskBuilder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accent_colour': value.accentColour,
        'name': value.name,
        'primary_colour': value.primaryColour,
    };
}

