/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskGroupBuilder
 */
export interface TaskGroupBuilder {
    /**
     * The task group's name (3 -> 30 characters)
     * @type {string}
     * @memberof TaskGroupBuilder
     */
    name: string;
    /**
     * The position of the task group in the project
     * If this is lowest unused value is used (the
     * end of the list)
     * @type {number}
     * @memberof TaskGroupBuilder
     */
    position?: number | null;
}

/**
 * Check if a given object implements the TaskGroupBuilder interface.
 */
export function instanceOfTaskGroupBuilder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TaskGroupBuilderFromJSON(json: any): TaskGroupBuilder {
    return TaskGroupBuilderFromJSONTyped(json, false);
}

export function TaskGroupBuilderFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskGroupBuilder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'position': !exists(json, 'position') ? undefined : json['position'],
    };
}

export function TaskGroupBuilderToJSON(value?: TaskGroupBuilder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'position': value.position,
    };
}

