/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationAction
 */
export interface NotificationAction {
    /**
     * The endpoint to perform the action
     * @type {string}
     * @memberof NotificationAction
     */
    actionEndpoint: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationAction
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationAction
     */
    notificationId: string;
    /**
     * The title (description) of the action
     * @type {string}
     * @memberof NotificationAction
     */
    title: string;
}

/**
 * Check if a given object implements the NotificationAction interface.
 */
export function instanceOfNotificationAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "actionEndpoint" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "notificationId" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function NotificationActionFromJSON(json: any): NotificationAction {
    return NotificationActionFromJSONTyped(json, false);
}

export function NotificationActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actionEndpoint': json['action_endpoint'],
        'id': json['id'],
        'notificationId': json['notification_id'],
        'title': json['title'],
    };
}

export function NotificationActionToJSON(value?: NotificationAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action_endpoint': value.actionEndpoint,
        'id': value.id,
        'notification_id': value.notificationId,
        'title': value.title,
    };
}

