/* tslint:disable */
/* eslint-disable */
/**
 * Nine Yards REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rabbitminers@zohomail.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * The project's icon's url
     * @type {string}
     * @memberof Project
     */
    iconUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    id: string;
    /**
     * The project's name (3 -> 30 charachters)
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    owner: string;
    /**
     * The permissions of non-member by default this is none.
     * And a membership would be needed to interact with the
     * project in any capcacity.
     * @type {number}
     * @memberof Project
     */
    publicPermissions: number;
}

/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iconUrl" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "publicPermissions" in value;

    return isInstance;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iconUrl': json['icon_url'],
        'id': json['id'],
        'name': json['name'],
        'owner': json['owner'],
        'publicPermissions': json['public_permissions'],
    };
}

export function ProjectToJSON(value?: Project | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'icon_url': value.iconUrl,
        'id': value.id,
        'name': value.name,
        'owner': value.owner,
        'public_permissions': value.publicPermissions,
    };
}

